### ISSUE TITLE
DB Migrations

### ISSUE THREAD

**Issue by AuHau** [rsksmart/rif-marketplace-cache#1]
Before release, there should be created proper migrations:

https://github.com/sequelize/cli/blob/master/docs/README.md
https://sequelize.org/v5/manual/migrations.html
!!! https://github.com/feathersjs-ecosystem/feathers-sequelize#migrations

**Comment by AuHau** [comment]
Heh it is already "critical" 😅 Can't get much higher than this 😝
I will work on it hopefully on beginning of next week.

**Comment by julianmrodri** [comment]
Yes no worries. I thought it was mandatory for Testnet but we can work around it.

**Comment by julianmrodri** [comment]
Actually shoulnt be Critical

**Comment by julianmrodri** [comment]
I think we can close this for some reason didnt ge tclose when merging PR.

**Comment by AuHau** [comment]
Yeah, we can. It was only mentioned in the PR not [linked](https://docs.github.com/en/enterprise/2.16/user/github/managing-your-work-on-github/closing-issues-using-keywords#about-issue-references)
