### ISSUE TITLE
Drop conf package

### ISSUE THREAD

**Issue by AuHau** [rsksmart/rif-marketplace-cache#115]
Currently Cache uses [`conf`](https://github.com/sindresorhus/conf) package for storing some data (last processed blocks) outside of database, which might be confusing for people using this project (for example they will truncate database and the data won't be re-loaded because the Cache will use the last-processed-block from conf which will be different the `null`)

All data should be stored in DB.

**Comment by julianmrodri** [comment]
Super important thanks for noting Adam.
