### ISSUE TITLE
Refactor EventEmitter to separate package

### ISSUE THREAD

**Issue by AuHau** [rsksmart/rif-marketplace-cache#138]
The confirmation and blockchain event handling can be beneficial for more people, so we should release it as separate package.

I will need it for the Pinning Service anyway.

**Comment by AuHau** [comment]
Future repo: https://github.com/rsksmart/web3-events

**Comment by julianmrodri** [comment]
@AuHau maybe we can close this issue now that `web3-events` is implemented?

**Comment by AuHau** [comment]
👍
