### ISSUE TITLE
Add topics for RNS

### ISSUE THREAD

**Issue by AuHau** [rsksmart/rif-marketplace-cache#244]
With the PR https://github.com/rsksmart/rif-marketplace-cache/pull/243 there is new support for Event's topics. This should filter the events based on the Event's signature to only those we are interested directly on the RSK node and not fetch everything. 

I don't know what are the RNS's events signatures so please add those. You can see the example https://github.com/rsksmart/rif-marketplace-cache/pull/243/files#diff-0b4d6dead760d533c5ef6036feb32d4bR47

**Comment by julianmrodri** [comment]
Adam is this mandatory? Do we have to refactor the `config` files or should work as expected?
Also.. in our case we have more than one contract. Are the Topics defined at the `rns` level like in Storage or we should do it under each contract?

**Comment by AuHau** [comment]
They are not mandatory, but strongly suggested. You define time in each RNS's listening contract (e.g. `rns.owner` etc.), no refactor is needed. I would suggest to look at the example that I gave above and if you anytime have doubts about the config structure, checkout the [Config interface](https://github.com/rsksmart/rif-marketplace-cache/blob/2986aefdf1cdbc323d08d9da3800c51fed64b536/src/definitions.ts#L110) that we maintain to keep the expected Config's structure and capabilities.
