### ISSUE TITLE
Handle Execution of Events in Sync mode

### ISSUE THREAD

**Issue by julianmrodri** [rsksmart/rif-marketplace-cache#294]
* Due to the fact that we are handling events async there could be situations where events are not processed in the correct order. We need to be able to guarantee that they are processed in the correct order to avoid inconsistencies in the Cache..
One option is to process in Sync mode, using Queue to ensure depending events are processed as they are emitted.

**Comment by julianmrodri** [comment]
@AuHau I believe this was fixed by `web3-events` right?

**Comment by AuHau** [comment]
Well only for the Storage part. We can close it and move the RNS part to the #366
