### ISSUE TITLE
Group RNS events listening for serial processing

### ISSUE THREAD

**Issue by julianmrodri** [rsksmart/rif-marketplace-cache#366]
As part of the refactor we did of using `web3-events` library we still have to implement the required changes for the RNS module to ensure it behaves as expected.

**Comment by AuHau** [comment]
Blocked by https://github.com/rsksmart/web3-events/issues/12

**Comment by julianmrodri** [comment]
Removing the `blocked` as I understand we are already tackling this issue.

**Comment by jurajpiar** [comment]
Closed by [PR 460](https://github.com/rsksmart/rif-marketplace-cache/pull/460)
