### ISSUE TITLE
Notifications not processed because Agreement comes later

### ISSUE THREAD

**Issue by julianmrodri** [rsksmart/rif-marketplace-cache#415]
I experienced this situation where I created a Agreement, the file couldn't be pinned (due to our known size issue) but the ERROR message did not get populated in cache because apparently got there before the Agreement existed.

We need to find a way for this notifications to get to the Cache and end users. This was done locally using Ganache with a fixed block time, which is similar to what we will see in Testnet/Mainnet.

One question comes to my mind: Do we need to check for existing Agreement? Is this to prevent spam or messages not related to the service?

![image](https://user-images.githubusercontent.com/56316686/100187409-cea11e80-2ec6-11eb-8d83-24678a9efd52.png)

**Comment by julianmrodri** [comment]
Could it be related to number of confirmations? In this case both Pinner and Cache had same amount of confirmations for `storage` contract. Maybe Pinner needs to wait more.

**Comment by AuHau** [comment]
Hmm interesting, I guess race condition can happen here. We will have to tackle this.

@nduchak what do you think? 

If the check for the existing Agreement has to be there then I would propose to create a closure that will repeat the message handling few times until either it succeeds or runs out of tries...

**Comment by julianmrodri** [comment]
From devops team:  probably the less invasive approach is to also pull `supportColors` from `colors` and guard `addColors` with `if (supportColors() !== false)`

**Comment by nduchak** [comment]
Hmm... Can we just store this notification(no agreement notifications), and then when the agreement comes(in agreement handler) just query all unprocessed notification for this agreement and process them. What do you think @AuHau ?

**Comment by AuHau** [comment]
@julianmrodri that is not related to this issue.

**Comment by AuHau** [comment]
@nduchak well that will work, but then we will need another GC process for collecting events whose agreements were never created...

**Comment by nduchak** [comment]
Is this a case, if we receive notification from pinner that's mean that pinner already receive agreement new event, which means that cache should receive it also?

**Comment by AuHau** [comment]
Well yes, but if there is no check about agreement's existence and no GC, somebody could just spam us with these messages and we would never clean up...

**Comment by nduchak** [comment]
Yea, good point. Looks like that some of the providers can make this kind of spam. So how to proceed?
Make clojure with retry or make processing on agreement new event and GC?

**Comment by AuHau** [comment]
Tbh. not sure. I like the closure approach bit more, but I will leave it up to you ;-)

**Comment by nduchak** [comment]
Ok, i will go with clojure as its require less code
