### ISSUE TITLE
Support no colors output

### ISSUE THREAD

**Issue by AuHau** [rsksmart/rif-marketplace-cache#417]
DevOps are collecting logs from Container's STDOUT. We should enable configure no colors output when env variable `LOG_NO_COLORS` is set.

**Comment by julianmrodri** [comment]
From devops team:  probably the less invasive approach is to also pull `supportColors` from `colors` and guard `addColors` with `if (supportColors() !== false)`

**Comment by julianmrodri** [comment]
This change should also be implemented in **Pinner** and **File Upload service** right?

**Comment by AuHau** [comment]
Yes
