### ISSUE TITLE
Unable to query nested models

### ISSUE THREAD

**Issue by jurajpiar** [rsksmart/rif-marketplace-cache#50]
This [feathers-sequelize](https://github.com/feathersjs-ecosystem/feathers-sequelize#setting-paramssequelizeinclude) readme section describes a way to fix this issue.

Blocking [Cannot search offers by name #53](https://github.com/rsksmart/rif-marketplace-ui/issues/53)

**Comment by AuHau** [comment]
I believe this is not really a problem of the Cache as it is not something that needs to be specifically supported by Cache, this should be supported by Sequalize by default. 

I think that we are either running into a limitation of Feather query system or we still have not discovered the way how to build the right query. I would say lets ask somewhere...
